LANG_SUFFIX=asm
FLAGS_COMPILER2TARGET=-I ../../ch01_bootsector/nasm -o
FILES_SOURCE_DEPENDENCIES=common_timer_isr.asm ../../ch01_bootsector/nasm/common.asm ../../ch01_bootsector/nasm/common_bios.asm

include ../../ch01_bootsector/common.mk
