CH01_BASE_DIR=../../ch01_bootsector/
CH01_LANG_BASE_DIR=$(CH01_BASE_DIR)$(LANG_SUFFIX)/
FLAGS_COMPILER2TARGET=-I $(CH01_LANG_BASE_DIR) -o
CH02_BASE_DIR=../../ch02_timer/
CH02_LANG_BASE_DIR=$(CH02_BASE_DIR)$(LANG_SUFFIX)/
CH02_TITLE=timer_isr
CH01_TITLE=bootsector
FILES_SOURCE_DEPENDENCIES=$(CH02_LANG_BASE_DIR)common_$(CH02_TITLE).$(LANG_SUFFIX) $(CH01_LANG_BASE_DIR)common_$(CH01_TITLE).$(LANG_SUFFIX) $(CH01_LANG_BASE_DIR)common_bios.$(LANG_SUFFIX)

include $(CH01_BASE_DIR)common.mk