FILES_SOURCE_DEPENDENCIES=../../ch01_bootsector/v/common_bios.v
FILES_SOURCE_ADDITIONAL_DEPENDENCIES=common_timer_isr.v main.v
FILES_SOURCE_SET = .
EXE_LANG_COMPILER=v
FLAGS_LANG_TO_C=-freestanding -o 
FILES_SOURCE_ADDTIONAL_DEPENDENCIES = main.v

include ../common.mk
